#!/bin/sh
# Calculate alloy profile along z-axis, choose artificially high potential

efpqw -N 10 -y 10

# Convert alloy concentration `x' into effective mass `m', specify constant
# mass
efxv -m 0.067

# Implement shooting technique
efss --nst-max 10
