#!/bin/sh
# Calculate alloy profile along z-axis, choose artificially high potential

efpqw --xmax 10 --nz 1000

# Convert alloy concentration `x' into effective mass `m', specify constant
# mass
efxv -m 0.067

# Implement shooting technique
efss --nst-max 10
