#!/bin/sh
# Calculate alloy profile along z-axis, choose artificially high potential

efpqw -N 10 -y 10

# Convert alloy concentration `x' into potential `v' 

efxv

# Convert alloy concentration `x' into effective mass `m', specify constant
# mass

efxm -m 0.067

# Implement shooting technique

efshoot -s 10

# Calculate wave functions

efwf
