#!/bin/sh
# Calculation of the mean e-e scattering rate over two subband populations
# as a function of well width
# Define output file

OUT=cc-N.r

# Initialise files

rm -f $OUT

# Scattering rate codes (at the moment) are angled towards numerical
# solutions and require a potential barrier height as an upper
# for integration, so define an artificial structure
# making sure it contains the same number of points as below

echo 100 1.0 0.0 > s.r
echo 100 0.0 0.0 >> s.r
echo 100 1.0 0.0 >> s.r

# Now convert structure into potential data

efsx
efxv

# Define the well width

LW=300

# Generate infinitely deep well solutions

efiw -L $LW -N 300 -s 2

# Define the required e-e rate

echo 2 2 2 2 > rr.r

# Loop over subband populations

for N in 1 2 5 10 20 50 100 
do
{
 # Write carrier density to file

 echo 1 $N > N.r
 echo 2 $N >> N.r

 # and save in output file

 echo -n $N >> $OUT

 # Loop over different temperatures

 for T in 4 77 300
 do
 {
 # Calculate the distribution functions

 sbp -T $T
 
 # Calculate carrier-carrier (e-e) scattering rate

 srcc -T $T

 # Sort and store in output file

 nawk '/2 2 2 2/{printf(" %e",$5)}' ccABCD.r >> $OUT
 }
 done

# End line in output file

echo -n -e "\n" >> $OUT

}
done
