#!/bin/sh
# Bulk Si calculation
# Write crystal basis to file `atoms.xyz' in XYZ format
# Note basis vectors are +/- (1/8,1/8,1/8) and A0=5.43
# Note also the atom type is defined as `SIcb' this selects the 
# Cohen and Bergstresser potentials

echo 2	> atoms.xyz
echo    >> atoms.xyz				# leave blank line
echo SIcb -0.67875 -0.67875 -0.67875 >> atoms.xyz
echo SIcb  0.67875  0.67875  0.67875 >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms


# Define k-vectors

echo 0.5 0.5 0.5  > k.r		# The L point
echo 0.4 0.4 0.4 >> k.r
echo 0.3 0.3 0.3 >> k.r
echo 0.2 0.2 0.2 >> k.r
echo 0.1 0.1 0.1 >> k.r
echo 0.0 0.0 0.0 >> k.r		# Gamma
echo 0.0 0.0 0.1 >> k.r
echo 0.0 0.0 0.2 >> k.r
echo 0.0 0.0 0.3 >> k.r
echo 0.0 0.0 0.4 >> k.r
echo 0.0 0.0 0.5 >> k.r
echo 0.0 0.0 0.6 >> k.r
echo 0.0 0.0 0.7 >> k.r
echo 0.0 0.0 0.8 >> k.r
echo 0.0 0.0 0.9 >> k.r
echo 0.0 0.0 1.0 >> k.r		# X

# Repeat calculation for different numbers of plane waves, selected
# by the maximum value of |G|

for Gmax in 1 1.8 2 3 3.4 3.5 4 4.4 4.5 4.9
do
{
 # create reciprocal lattice vectors

 rlv-fcc -g $Gmax
 
 # Implement pseudopotential calculation

 pplb -A 5.43 -n 1 -m 6

 # Gather first 6 eignenvalues together 

 ppee -n 1 -m 6
  
 # Need a sed line here to assign negative number to L->Gamma points

 mv Ek.r Ek.r.tmp
 sed '1,5s/+/-/' Ek.r.tmp >> Ek.r
 rm Ek.r.tmp

 # Save the Ek.r files and the G.r files

 mv Ek.r Ek-Gmax=$Gmax.r
 mv G.r G-Gmax=$Gmax.r

 # Tidy up

 rm ank.r Ek?.r Ek??.r
}
done
