#!/bin/sh
# Initialise files

rm -f Ee-lw.r Eh-lw.r Eb-lw.r EX0-lw.r

# Loop for different well widths

for LW in 20 60 100 
do
{
 efiw -N 300 -L $LW -m 0.096 -p e	# infinite well electron ground state
 cat Ee.r >> Ee-lw.r

 efiw -N 300 -L $LW -m 0.6 -p h		# infinite well hole ground state
 cat Eh.r >> Eh-lw.r

 ebe -e 10.6 -m 0.096 -n 0.6 -s 40 -w 0.601	# start variational calculation
 echo -n "$LW\t" >> EX0-lw.r		# write well width to file
 cat EX0.r >> EX0-lw.r			# send data to file
 cp p.r pLW=$LW.r

}
done
# Note the very wide wells and very narrow wells, needed to be recalculated
# with a greater number of wave function points, to obtain the necessary
# accuracy
