#!/bin/sh
# Initialise files

rm -f Ee-lw.r

# Loop for different well widths

for LW in `seq 10 10 200`
do
{
 # Calculate first 4 energy levels as a function of well width for GaAs
 efiw -L $LW -m 0.067 -s 3

 printf "%d\t" "$LW" >> Ee-lw.r	# write well width to file

 energies=`awk '{print $2}' < Ee.r`
 echo $energies >> Ee-lw.r

 # Repeat using nonparabolicity
 efiw -L $LW -m 0.067 -s 3 --alpha 0.701

 printf "%d\t" "$LW" >> Ee-lw-alpha.r	# write well width to file

 energies=`awk '{print $2}' < Ee.r`
 echo $energies >> Ee-lw-alpha.r
}
done
