#!/bin/sh
# Calculation of the mean e-e scattering rate over two subband populations
# as a function of well width
# Define output file

OUT=cc-LW.r

# Initialise files

rm -f $OUT

# Scattering rate codes (at the moment) are angled towards numerical
# solutions and require a potential barrier height as an upper
# for integration, so define an artificial structure
# making sure it contains the same number of points as below

echo 100 1.0 0.0 > s.r
echo 100 0.0 0.0 >> s.r
echo 100 1.0 0.0 >> s.r

# Now convert structure into potential data

efsx
efxv

# Define subband populations in file `N.r'
 
echo 1 1 > N.r
echo 2 1 >> N.r

# Define the required e-e rate

echo 2 2 1 1 > rr.r

# Loop over infinite well width

for LW in 100 200 300 400 500 600
do
{
 # Generate infinitely deep well solutions

 efiw -L $LW -N 300 -s 2

 # Save lowest two energies to file

 nawk '/1 /{E1=$2};/2 /{E2=$2};END{printf("%20.17e ",E2-E1)}' Ee.r >> $OUT

 # Loop over different temperatures

 for T in 4 77 300
 do
 {
 # Calculate the distribution functions

 sbp -T $T
 
 # Calculate carrier-carrier (e-e) scattering rate

 srcc -T $T

 # Sort and store in output file

 nawk '/2 2 1 1/{printf("%e ",$5)}' ccABCD.r >> $OUT
 }
 done

# End line in output file

echo -n -e "\n" >> $OUT

}
done
