#!/bin/ksh
# Transport through dot array calculation
# Initialise files

rm -f ank*.r Ek*.r

# Define the unit cell extent

NX=2
NY=2
NZ=2

# and the lattice constant in Angstrom

A0=5.65

# Create simple cube unit cell of (NX,NY,NZ) lattice constants

cszb -a SI -c SI -x $NX -y $NY -z $NZ

# Create quantum dot by substituting atoms explicitly

sed '3,10s/SI/GE/' atoms.xyz > atoms.tmp
mv atoms.tmp atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# Specify k-points for calculation, to calculate dispersion curves need more
# points than zone center, note with n_z=2, zone edge at 1/4 (2*pi/A0)

echo 0.0 0.0 0.0 > k.r
echo 0.0 0.0 0.025 >> k.r
echo 0.0 0.0 0.050 >> k.r
echo 0.0 0.0 0.075 >> k.r
echo 0.0 0.0 0.100 >> k.r
echo 0.0 0.0 0.125 >> k.r
echo 0.0 0.0 0.150 >> k.r
echo 0.0 0.0 0.175 >> k.r
echo 0.0 0.0 0.200 >> k.r
echo 0.0 0.0 0.225 >> k.r
echo 0.0 0.0 0.250 >> k.r

# Generate reciprocal lattice vectors for this simple cube, and sort

rlv-sc -x $NX -y $NY -z $NZ

ppsg

# Implement pseudopotential band structure calculation, use default lattice
# constant, output all valence band eigenfunctions.  Note the number of
# valence band states is twice the number of atoms in the basis

# Calculate all VB and lowest CB state

let N=2*$NX*$NY*$NZ*8
let M=2*$NX*$NY*$NZ*8+1

pplb -n $N -m $M 

# Collate top VB and bottom CB states

# Create dummy file with single line in to allow use of awk for the division

echo dummy line > dummy.file

for K in 0 1 2 3 4 5 6 7 8 9 10
do
{
 nawk "{printf(\"%f\",$K/40)}" dummy.file >> Ek.r
 nawk '{printf(" %f",$1)}' Ek$K.r >> Ek.r
 echo -n -e "\n" >> Ek.r
}
done

# Tidy up

#rm -f ank*.r
