#!/bin/sh
# Initialise files

rm -f Ee-mb.r

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.4

V=334.196

# Keep well width constant at 100 Angstom

LW=100

# Loop for different barrier heights

for MB in 0.01 0.02 0.03 0.04 0.05 0.06 0.067 0.07 0.08 0.09 0.10 0.20 0.50 1.0 2.0 5.0 10 20 50 100 200 500 1000
do
{
 echo -n -e "$MB\t" >> Ee-mb.r	# write potential to file

# Calculate ground state energy for different well and barrier masses
 efsqw -a $LW -m 0.067 -n $MB -V $V
 nawk '{printf("%8.3f\n",$2)}' Ee.r >> Ee-mb.r		# send data to file
}
done
