#!/bin/sh
# Define output file

OUT=E-N.r

# Initialise files

rm -f $OUT

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.2

V=334.196

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x, keep x=0.2

MB=0.1002

# Define well and barrier widths here

LW=100
LB=100

for N in 1 2 3 4
do
{
 # Write $N and the well and barrier widths to file---it's the only way
 # I can think of to pass these arguments to the awk script below

 echo $N $LW $LB > Nwells.r	

 # Write first barrier and initiate file

 echo 100 0.4 0.0 > s.r		

 # Could only think of an awk script as a replacement `for(i=1;i<N-1;i++)'
 # loop---I'm sure you must be able to do this within `/bin/sh'

 nawk '
		{Nwells=$1
		 LW=$2
		 LB=$3
		 while(Nwells-->1)
		 {printf("%i 0.0 0.0\n",LW)	
		  printf("%i 0.4 0.0\n",LB)	
		 }
		}
 ' Nwells.r >> s.r
		 
 # Write last well

 echo $LW 0.0 0.0 >> s.r

 # Followed by final barrier
 echo 100 0.4 0.0 >> s.r

 efsx			# generate alloy concentration as a function of z
 efxv			# generate potential data

 echo -n $N >> $OUT

 # Need a small energy difference to split nearly degenerate levels
 efss -d 0.001

 # Write energy to output file

 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT	
 echo -n -e "\n" >> $OUT
}
done

# To compare with infinite superlattice

# efkpsl -a $LW -b $LB -n $MB -V $V
