#!/bin/sh
# Define output file

OUT=E-LAMBDA.r

# Initialise files

rm -f Ee-LAMBDA*
rm -f v-LAMBDA*
rm -f $OUT

# Loop over depth parameter lambda

for LAMBDA in 0.01 0.02 0.05 0.1 0.2 0.5 0.75 1 1.5 2.0 5.0 10.0
do
{
 # Define length of Poschl-Teller potential
 L=300

 pth -a 0.05 -l $LAMBDA -L $L
 echo -n $LAMBDA >> $OUT

 # Save lowest two energies to file

 nawk '/1 /||/2 /{printf("\t%f",$2)}' Ee.r >> $OUT	
 mv Ee.r Ee-LAMBDA=$LAMBDA.r

 # Now perform numerical solution
 #
 # Need to add extra point
 L=301
 # Then generate artificial s.r file, necessary to produce mass data
 echo $L 0.0 0.0 > s.r
 efsx			# generates z-data suitable for numerical solution
 efxm -m 0.067		# generate constant mass versus z data
 efshoot -s 2		# calculate 2 lowest energy levels
 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT
 echo -n -e "\n" >> $OUT
 #mv v.r v-LAMBDA=$LAMBDA.r
 cp v.r v-LAMBDA=$LAMBDA.r
}
done
