#!/bin/sh
# Second example, calculation of LO phonon emission scattering rate for 
# an electron in the second subband of an infinite quantum well, for a 
# variety of well widths
# Define temperature

T=77

# Scattering rate codes (at the moment) are angled towards numerical
# solutions and require a potential barrier height as an upper
# for integration, so define an artificial structure
# making sure it contains the same number of points as below

echo 100 1.0 0.0 > s.r
echo 100 0.0 0.0 >> s.r
echo 100 1.0 0.0 >> s.r

# Now convert structure into potential data

efsx
efxv

# Define required e-LO phonon rates 

echo 2 1 > rrp.r
 
for LW in 100 200 300 400 500 600
do
{
 efiw -L $LW -N 300 -s 2

 # Calculate electron LO phonon rates
 
 srelo -T $T

 # Save the output files

 mv LOe21.r LOe21-$LW.r
}
done
