language: cpp
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libarmadillo-dev
      - libatlas-base-dev
      - libboost-program-options-dev
      - libgsl0-dev
      - liblapack-dev
      - libxml++2.6-dev

before_script:
  - git submodule update --init

script: cmake . && make && ctest -V
