#!/bin/sh
# Initialise files

rm -f Ee-k.r

# Read well and barrier width from command line

LW=$1
LB=$2

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.4

V=334.1965

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x

MB=0.1002

# Loop for carrier momentum

for K in `seq -2.0 0.1 2.0`
do
{
 printf "%e\t" $K >> Ee-k.r	# write wave vector to file

 # Calculate energies for different wave vectors
 efkpsl -a $LW -b $LB -m 0.067 -n $MB --potential $V -k $K -s 1
 nawk '{printf("%9.3f\n",$2)}' Ee.r >> Ee-k.r		# send data to file
}
done

