#! /bin/sh

# Set fixed parameters
L=200 # Well-width (angstrom)
nst=3 # Number of states to find

# Find first three states in an infinite well
efiw -L $L -s $nst
dos
mv rho.r rho-parabolic.r

# Repeat for a nonparabolic well
alpha=0.701
efiw -L $L -s $nst --alpha $alpha
dos --alpha $alpha
mv rho.r rho-np.r
