#!/bin/sh
# Use total time 200s diffusant profile from previous section as initial
# profile

cp ../sec7/x-t=100.r x.r

# Run diffusion `simulation' for various times

for t in 0 10 20 50 100 200
do
{

 # Use diffusion coefficient defined in function `dox'

 gde -a 2 -d 0.001 -t $t
 
 # Store diffusion profiles

 cp X.r x-t=$t.r

 # With particular form of dox.c employed cannot calculate cumulative
 # effect, have to calculate each one in turn
}
done
