#!/bin/ksh
# Superlattice as a perturbation calculation for GaAs/AlAs---the
# perpendicular dispersion.
# Initialise files

rm -f ank*.r Ek*.r

# Define output file and initialise

OUTPUT=E-xi.r
rm -f $OUTPUT

# Solve bulk band structure for this superlattice k-point, use Mader and
# Zunger potentials

#First generate atomic positions in bulk

echo 2  > atoms.xyz
echo   >> atoms.xyz                            # leave blank line
echo GAASmz -0.70625 -0.70625 -0.70625 >> atoms.xyz
echo ASGAmz  0.70625  0.70625  0.70625 >> atoms.xyz

# Generate reciprocal latice vectors, and sort them

rlv-fcc 

ppsg

# Define a fixed superlattice period

NZ=10

# Create `single-spiral' unit cell of the unperturbed atoms

csss -a ASGAmz -c GAASmz -z $NZ

# Now create superlattice by swapping atoms

rm -f atomsp.xyz atoms.tmp	# initialise files
let A=2*NZ+3		# the first atom to be swapped
let B=4*NZ+2		# the last atom to be swapped
sed "$A,$B s/GAASmz/ALGAAS20/" atoms.xyz >> atoms.tmp
sed "$A,$B s/ASGAmz/ASALGA20/" atoms.tmp >> atomsp.xyz

# Convert also to pdb format for visual check

xyz2pdb atomsp

# Now loop over the electron wave vector in the superlattice Brillouin zone

for K in 0 0.2 0.4 0.6 0.8 1.0
do
{
 # Create bulk wave vectors required for superlattice calculation

 slk -k $K -z $NZ

 # Implement pseudopotential band structure calculation, use default lattice
 # constant, just use 1 CB in basis set

 pplb -n 5 -m 5 -w

 # Implement superlattice calculation, output lowest two states only

 ppsl -n 1 -m 2

 # Collate lowest conduction band energy levels.  Bulk GaAs calculation
 # gave top of the valence band as -5.505446 eV, hence add this to all
 # values

 echo -n $K >> $OUTPUT	# enter electron wavevector first

 nawk '{printf("%10.6f",$1+5.505446)}' Exi.r >> $OUTPUT

 echo -n -e "\n" >> $OUTPUT	# end line
}
done
# Tidy up

rm -f Ek*.r ank*.r
