#!/bin/sh
set -e

# Initialise files
rm -f Ef-T*.r N.r FD*.r N?-T.r N-all-T.r

# Solve single quantum well
efiw -L 200 -s 10

# Set the global population
N=10

# Need to artificially create a file v.r containing a barrier height,
# this used as a cut-off energy for population calculations
echo 0.00000 1.60219e-19 > v.r	# i.e., 1eV

alpha=0.701 # Nonparabolicity parameter for GaAs [1/eV]

# Loop for different temperatures
for T in `seq 10 10 1000`
do
    sbp -f --global-population $N -T $T --alpha $alpha
    printf "%d\t" $T >> Ef-T-global.r
    awk '/1\t/{printf("%8.3f\n", $2)}' Ef.r >> Ef-T-global.r
    N1=`awk '/1\t/{printf("%8.3f\n", $2)}' N-out.r`
    N2=`awk '/2\t/{printf("%8.3f\n", $2)}' N-out.r`
    N3=`awk '/3\t/{printf("%8.3f\n", $2)}' N-out.r`
    N4=`awk '/4\t/{printf("%8.3f\n", $2)}' N-out.r`
    N5=`awk '/5\t/{printf("%8.3f\n", $2)}' N-out.r`
    N6=`awk '/6\t/{printf("%8.3f\n", $2)}' N-out.r`

    printf "%d\t%8.3f\n" $T $N1 >> N1-T.r
    printf "%d\t%8.3f\n" $T $N2 >> N2-T.r
    printf "%d\t%8.3f\n" $T $N3 >> N3-T.r
    printf "%d\t%8.3f\n" $T $N4 >> N4-T.r

    # Find total populations up to, and including each subband
    N2all=`echo "$N1 + $N2"|bc`
    N3all=`echo "$N2all + $N3"|bc`
    N4all=`echo "$N3all + $N4"|bc`
    N5all=`echo "$N4all + $N5"|bc`
    N6all=`echo "$N5all + $N6"|bc`

    printf "%d\t%8.3f\t%8.3f\t%8.3f\t%8.3f\t%8.3f\t%8.3f\n" $T $N1 $N2all $N3all $N4all $N5all $N6all >> N-all-T.r
done
