#!/bin/sh
# 3D trial wave fucntion donor binding energy calculationas a function of
# well width for different barrier heights
# Define the barrier alloy concentration

X=0.1

# Define output file

OUTPUT=e-E-lw.r
OUTPUT2=lambda-lw.r

# Initialise files

rm -f $OUTPUT $OUTPUT2

# Create a dummy file with a single link of junk in, in order to use awk
# later

echo junk > dummy.file

# Loop over well width

for LW in 10 20 30 40 50 60 80 100 140 180 220 260 300 400 500 600 800 1000
do
{
# Define structure

echo 200 $X 0.0   > s.r
echo $LW 0.0 0.0 >> s.r
echo 200 $X 0.0  >> s.r

# Generate alloy profile

efsx

# Generate potential profile for Ga(1-x)Al(x)As, can use defaults

efxv 

# Calculate electron energy for same quantum well but without donor

efxm -m 0.067			# generate constant mass data 

efshoot				# calculate electron energy without donor
efwf				# generate wave functions

# Create r_d.r with single entry at centre of well

gawk "{printf(\"%e\n\",(200+$LW/2)/1e+10)}" dummy.file > r_i.r

# Start donor binding energy calculation

./i0 -S 2s

# Store Bohr radii as a function of well width too

echo -e -n $LW >> $OUTPUT2

# Append lambda

gawk '{printf(" %e\n",$2)}' l.r >> $OUTPUT2

# Store data in e-E-lw.r file, i.e. energy with donor (from e.r), energy
# without donor (from Ee.r) versus well width (lw)

echo -e -n $LW >> $OUTPUT

# Append energy with donor present

gawk '{printf(" %e",$2)}' e.r >> $OUTPUT

# Append energy without donor present

gawk '{printf(" %20.17e\n",$2)}' Ee.r >> $OUTPUT

}
done

# Just run quck awk script to calculate binding energy

gawk '{printf("%f %20.17e\n",$1,$3-$2)}' $OUTPUT > Eb-lw.r
