#!/bin/ksh
# Atomic positions for a pyramidal quantum dot calculation

# Define the unit cell extent

NX=20
NY=20
NZ=20

# and the lattice constant in Angstrom

A0=5.65

# Create simple cube unit cell of (NX,NY,NZ) lattice constants

cszb -a SI -c SI -x $NX -y $NY -z $NZ

# Now create quantum dot by swapping atoms

mv atoms.xyz atoms.tmp		# Create temporary storage

nawk -v BARRIER=1 -v BASE=18 -v HEIGHT=18 -v A0=5.65 -f cspd.awk atoms.tmp > atoms1.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms1

# Do a second geometry too

nawk -v BARRIER=1 -v BASE=18 -v HEIGHT=10 -v A0=5.65 -f cspd.awk atoms.tmp > atoms2.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms2

# Tidy up

rm -f atoms.tmp

