#!/bin/sh
# Generate the potentials of Mader and Zunger for GA in GAAS

ppvfq -a GAASmz -g 5

# Now calculate potentials of Mader and Zunger for AS in GAAS

ppvfq -a ASGAmz -g 5

# Now AlAs

ppvfq -a ALASmz -g 5
ppvfq -a ASALmz -g 5
