#!/bin/sh
# Loop over barrier concentrations

# Define alloy components X and Y in In(1-x-y)Al(x)Ga(y)As for both well
# and barrier

# Quantum wells, In(0.53)Ga(0.47)As

Yw=0.47
Xw=0.0

# Barriers, In(0.52)Al(0.48)As

Yb=0.0
Xb=0.48

# Define output file

OUT=E-LW.r

# Initialise files

rm -f $OUT D$OUT

# Loop over well width

for LW in 20 30 40 50 60 80 100 120 140 160 180 200
do
{

 # First generate structure definition `s.r' file
 echo 200 $Xb $Yb > s.r
 echo $LW $Xw $Yw >> s.r
 echo 200 $Xb $Yb >> s.r
 
 # Remember to switch material system

 efsx			# generate alloy concentration as a function of z
 efxv -M inalgaas 	# generate potential data, and bandgap
 
 echo -n $LW >> $OUT

 # Calculate ground state energy with band non-parabolicity

 efshoot -a

 # Write energy to output file

 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT	

 # Calculate wave function too

 #efwf -a 
 #mv wf_e1.r wf_e1-LW=$LW.r

 # Calculate ground state energy without band non-parabolicity

 efshoot 

 # Write energy to output file

 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT	

 echo -n -e "\n" >> $OUT	# terminate line
 }
 done # LW

 # Now calculate difference between `with' and `without' band non-parabolicity
 # and write to the new output file DE-LW.r

 nawk '{printf("%f \t%f\n",$1,$2-$3)}' $OUT >> D$OUT	
