#!/bin/sh

# Initialise files
rm -f Ee-mb.r

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.4
V=334.1965

# TODO: Read well width in from command line
LW=100 # Well width [angstrom]
MW=0.067 # Well mass (GaAs)

# Loop for different barrier masses
for iMB in `seq -2 0.1 3`
do
{
 # Generate barrier mass exponentially so we get a smooth curve
 MB=`echo $iMB | awk '{print 10^$1}'`
 echo -n -e "$MB\t" >> Ee-mb.r	# write potential to file

 # Calculate ground state energy for different well and barrier masses
 efsqw -a $LW -m $MW -n $MB --potential $V
 awk '{printf("%8.3f\n",$2)}' Ee.r >> Ee-mb.r		# send data to file
}
done

mv Ee-mb.r Ee-mb$LW.r
