#!/bin/ksh
# 1 Ge atom `tiny quantum dot' calculation
# Initialise files

rm -f ank*.r Ek*.r

# Define the unit cell extent

NX=2
NY=2
NZ=2

# and the lattice constant in Angstrom

A0=5.65

# Create simple cube unit cell of (NX,NY,NZ) lattice constants

cszb -a SI -c SI -x $NX -y $NY -z $NZ

# Create quantum dot by substituting atoms explicitly

sed '3s/SI/GE/' atoms.xyz > atoms.tmp
mv atoms.tmp atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# Specify k-points for calculation, note only want zone center

echo 0.0 0.0 0.0 > k.r

# Generate reciprocal lattice vectors for this simple cube, and sort

rlv-sc -x $NX -y $NY -z $NZ

ppsg

# Implement pseudopotential band structure calculation, use default lattice
# constant, output all valence band eigenfunctions.  Note the number of
# valence band states is twice the number of atoms in the basis

# Calculate all VB and lowest CB state

let N=2*$NX*$NY*$NZ*8
let M=2*$NX*$NY*$NZ*8+1

pplb -n 1 -m $M -w

# Calculate the charge density across the z=0 plane (dissects the
# cation-anion bond) sum over all VB states

mv ank0.r ank.r
ppcd -x -1.125 -X 0.875 -y -1.125 -Y 0.875 -z 0 -Z 0 -n 1 -m $N

# Tidy up

#rm -f ank*.r
