#!/bin/sh
# Initialise files

rm -f Ee-lw.r Eh-lw.r Eb-lw.r EX0-lw.r

# Loop for different well widths

for LW in 0.1 0.5 1 2 5 10 20 30 40 50 60 70 80 90 100 120 140 160 180 200 300 400 500 600 800 1000;
do
{
 efiw -N 300 -L $LW -m 0.096 -p e	# infinite well electron ground state
 cat Ee.r >> Ee-lw.r

 efiw -N 300 -L $LW -m 0.6 -p h		# infinite well hole ground state
 cat Eh.r >> Eh-lw.r

 ebe -e 10.6 -m 0.096 -n 0.6 -s 30 	# start variational calculation
 echo -n -e "$LW\t" >> EX0-lw.r		# write well width to file
 cat EX0.r >> EX0-lw.r			# send data to file

}
done
# Note the very wide wells and very narrow wells, needed to be recalculated
# with a greater number of wave function points, to obtain the necessary
# accuracy
