#!/bin/sh
# Initialise files

#rm -f s.r Ee-lw.r Eh-lw.r EX0-lw.r

# Loop for different well widths

for LW in 70 #20 30 40 50 60 70 80 90 100 120 140 160 180 200 
do
{
 echo 200 0.2 0.0 > s.r		# Generate s.r file
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.2 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.2 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.2 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.2 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo 200 0.2 0.0 >> s.r

 efsx				# Generate x versus z data

 efxv 				# Generate potential file v.r
 efxm -m 0.067			# Constant effective mass
 efshoot 			# Solve Schrodinger equation
 efwf				# Calculate wave function
 cat Ee.r >> Ee-lw.r
 cp wf_e1.r wf=$LW\_e1.r	# Save wave functions for later analysis

 efxv -p h
 efxm -m 0.62 -p h
 efshoot -p h -d 0.0001
 efwf -p h
 cat Eh.r >> Eh-lw.r
 cp wf_h1.r wf=$LW\_h1.r	

 ebe -s 85 -w 0.001 -x 0.01 	# start variational calculation
 echo -n -e "$LW\t" >> EX0-lw.r	# write well width to file
 cat EX0.r >> EX0-lw.r		# send data to file

}
done
