#!/bin/ksh
# GaAs/AlAs superlattice calculation with the continuous potentials of 
# Mader and # Zunger et al. Phys. Rev. B (1994)
# Note also the atom types are defined as `GAASmz' and `ASGAmz'
# this selects the Ga in GaAs and As in GaAs potentials
# Define output file and initialise

OUTPUT=E-Nz.r
rm -f $OUTPUT

# Define k-vectors

echo 0.0 0.0 0.0 > k.r

# Loop over superlattice period

for NZ in 1 2 3 4 5 6 7 8 9 10 12 14 16 18
do
{
# Create `single-spiral' unit cell akin to superlattice

csss -a ASGAmz -c GAASmz -z $NZ

# Now create superlattice by swapping atoms

mv atoms.xyz atoms.tmp
let A=2*NZ+3		# the first atom to be swapped
let B=4*NZ+2		# the last atom to be swapped
sed "$A,$B s/GA/AL/" atoms.tmp >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# create reciprocal lattice vectors, note use of default maximum |G|

rlv-ss -z $NZ

# Sort the G vectors into ascending order

ppsg

# Implement pseudopotential calculation, note use of default lattice constant

pplb -n 1 -m 288

# Collate top valence band and bottom conduction bands, note
# a structure with a period of NZ has 4NZ atoms, each of which contributes 
# two valence levels, hence the uppermost VB level is the 8NZ.

let N=8*NZ	# top valence band
let M=8*NZ+1	# bottom conduction band

ppee -n $N -m $M
 
# Now collect energy levels in file

echo -n $NZ >> $OUTPUT

# Bulk GaAs calcualtion gave top of valence band as -5.505446 eV, hence add
# this amount to all energy levels, and write levels to output file

nawk '{printf("%10.6f %10.6f\n",$2+5.505446,$3+5.505446)}' Ek.r >> $OUTPUT

}
done

# Tidy up

rm -f ank?.r Ek*.r 
