#!/bin/sh
# Define output file

OUT=E-LB.r

# Initialise files

rm -f $OUT

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.2

V=167.0985

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x, keep x=0.2

MB=0.0836

# Define well width here

LW=60

# Loop over barrier width, execute out of order to retain 40Angstrom data

for LB in 10 20 30 50 60 70 80 90 100 120 140 160 180 200 40
do
{
 echo -n $LB >> $OUT

 # perform numerical solution
 #
 # First generate structure definition `s.r' file
 echo 200 0.2 0.0 > s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LB 0.2 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo 200 0.2 0.0 >> s.r

 efsx			# generate alloy concentration as a function of z
 efxv			# generate potential data

 # Need a small energy difference to split nearly degenerate levels
 efshoot -s 2 -d 0.01		# calculate 2 lowest energy levels
 nawk '/1 /||/2 /{printf("\t%f",$2)}' Ee.r >> $OUT	
 echo -n -e "\n" >> $OUT
}
done
