#!/bin/sh
# 3D trial wave fucntion donor binding energy calculationas a function of
# well width for different barrier heights
# Define the barrier alloy concentration

X=0.1

# Define structure

echo 200 $X 0.0   > s.r
echo 100 0.0 0.0 >> s.r
echo 200 $X 0.0  >> s.r

# Generate alloy profile

efsx

# Generate potential profile for Ga(1-x)Al(x)As, can use defaults

efxv 

# Calculate electron energy for same quantum well but without donor

efxm -m 0.067			# generate constant mass data 

efshoot				# calculate electron energy without donor
efwf				# generate wave functions

# Create r_i.r with donors across barrier-well-barrier structure

echo '
0e-10
30e-10
60e-10
90e-10
120e-10
150e-10
180e-10
210e-10
240e-10
250e-10
260e-10
290e-10
320e-10' > r_i.r

# Start donor binding energy calculation

i0
