#!/bin/sh
set -e

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
X=0.1

# Allow barrier composition to be read from command-line
if [ "x$1" != "x" ]; then
    X=$1
fi

# Use V=0.67*1247*x
V=`echo $X | awk '{print 0.67*1247*$1}'`

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x
MB=`echo $X | awk '{print 0.067+0.083*$1}'`

# Keep well width constant
L2=50

tdb -b $L2 --potential $V -n $MB
mv T.r TX=$X.r
