#!/bin/sh
# Initialise files

#rm -f s.r Ee-lw.r Eh-lw.r EX0-lw.r

# Loop for different well widths

for LW in 20 30 40 50 60 70 80 90 100 120 140 160 180 200 
do
{
 echo 200 0.1 0.0 > s.r		# Generate s.r file
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.1 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.1 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.1 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo $LW 0.1 0.0 >> s.r
 echo $LW 0.0 0.0 >> s.r
 echo 200 0.1 0.0 >> s.r

 efsx				# Generate x versus z data

 efxv -m 0.067			# Constant effective mass
 efss 			# Solve Schrodinger equation
 cat Ee.r >> Ee-lw.r
 cp wf_e1.r wf=$LW\_e1.r	# Save wave functions for later analysis

 efxv -m 0.62 -p h 
 efss -p h -d 0.001		# May need smaller step to resolve miniband
				#  at larger LW
 cat Eh.r >> Eh-lw.r
 cp wf_h1.r wf=$LW\_h1.r	

 ebe -s 80 -w 0.001 -x 0.01 	# start variational calculation
 echo -n -e "$LW\t" >> EX0-lw.r	# write well width to file
 cat EX0.r >> EX0-lw.r		# send data to file
}
done
