#!/bin/sh
# Define output file

OUT=Ee-t.r

# Initialise files

rm -f $OUT

# Define initial dopant profile using `efsx'

echo 200 1.0 0.0 > s.r
echo 200 0.0 0.0 >> s.r

# Run diffusion `simulation' for various times

#for t in 0 10 20 50 100 200 500 1000
for t in 2000 5000
do
{
 # Re-generate initial alloy concentration (diffusant) profile

 efsx

 # Use diffusion coefficient defined in function `dox'

 gde -a 2 -t $t
 
 # Store diffusion profiles

 cp X.r x-t=$t.r

}
done
