#!/bin/sh
# Bulk GaAs calculation
# Write crystal basis to file `atoms.xyz' in XYZ format
# Note basis vectors are +/- (1/8,1/8,1/8) and A0=5.65
# Note also the atom types are defined as `GAAScb' and `ASGAScb'
# this selects the Ga in GaAs and As in GaAs Cohen and Bergstresser (cb)
# potentials

echo 2	> atoms.xyz
echo    >> atoms.xyz				# leave blank line
echo GAAScb -0.70625 -0.70625 -0.70625 >> atoms.xyz
echo ASGAcb  0.70625  0.70625  0.70625 >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# Define k-vectors

echo 0.0 0.0 -0.010 >  k.r
echo 0.0 0.0 -0.008 >> k.r
echo 0.0 0.0 -0.006 >> k.r
echo 0.0 0.0 -0.004 >> k.r
echo 0.0 0.0 -0.002 >> k.r
echo 0.0 0.0  0.000 >> k.r		# Gamma
echo 0.0 0.0  0.002 >> k.r
echo 0.0 0.0  0.004 >> k.r
echo 0.0 0.0  0.006 >> k.r
echo 0.0 0.0  0.008 >> k.r
echo 0.0 0.0  0.010 >> k.r

# create reciprocal lattice vectors, note use of default maximum |G|

rlv-fcc

# Sort the G vectors into ascending order

ppsg

# Implement pseudopotential calculation, note use of default lattice constant

pplb -n 1 -m 5

# Extract lowest conduction band state only

ppee -n 5 -m 5
 
# Need a sed line here to assign negative number to the first 5 k points 

mv Ek.r Ek.r.tmp
sed '1,5s/+/-/' Ek.r.tmp >> Ek.r
rm Ek.r.tmp

# Tidy up

rm ank.r Ek?.r Ek??.r
