#!/bin/sh
# Initialise files

rm -f Ee-lw.r

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x

V=334.196

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x

MB=0.1002

# Loop for different well widths

for LW in 10 20 30 40 50 60 70 80 90 100 120 140 160 180 200 
do
{
 printf "%d\t" "$LW" >> Ee-lw.r	# write well width to file

# Calculate ground state energy for barrier mass (MB)=well mass (0.067)
 efsqw -a $LW -m 0.067 -n 0.067 --potential $V
 nawk '{printf("%8.3f",$2)}' Ee.r >> Ee-lw.r		# send data to file

# Calculate ground state energy for correct barrier mass 
 efsqw -a $LW -m 0.067 -n $MB --potential $V
 nawk '{printf("%8.3f\n",$2)}' Ee.r >> Ee-lw.r		# send data to file
}
done
