#!/bin/sh
# Bulk AlAs calculation with the recent continuous potentials of Mader and
# Zunger et al. Phys. Rev. B (1994)
# Write crystal basis to file `atoms.xyz' in XYZ format
# Note basis vectors are +/- (1/8,1/8,1/8) and A0=5.65
# Note also the atom types are defined as `ALASmz' and `ASALmz'
# this selects the Al in AlAs and As in AlAs potentials

echo 2	> atoms.xyz
echo    >> atoms.xyz				# leave blank line
echo ALASmz -0.70625 -0.70625 -0.70625 >> atoms.xyz
echo ASALmz  0.70625  0.70625  0.70625 >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# Define k-vectors

echo 0.5 0.5 0.5  > k.r		# The L point
echo 0.4 0.4 0.4 >> k.r
echo 0.3 0.3 0.3 >> k.r
echo 0.2 0.2 0.2 >> k.r
echo 0.1 0.1 0.1 >> k.r
echo 0.0 0.0 0.0 >> k.r		# Gamma
echo 0.0 0.0 0.1 >> k.r
echo 0.0 0.0 0.2 >> k.r
echo 0.0 0.0 0.3 >> k.r
echo 0.0 0.0 0.4 >> k.r
echo 0.0 0.0 0.5 >> k.r
echo 0.0 0.0 0.6 >> k.r
echo 0.0 0.0 0.7 >> k.r
echo 0.0 0.0 0.8 >> k.r
echo 0.0 0.0 0.9 >> k.r
echo 0.0 0.0 1.0 >> k.r		# X

# create reciprocal lattice vectors, note use of default maximum |G|

rlv-fcc

# Sort the G vectors into ascending order

ppsg

# Implement pseudopotential calculation, note use of default lattice constant

pplb -n 1 -m 6

# Gather first 6 eignenvalues together 

ppee -n 1 -m 6
 
# Need a sed line here to assign negative number to L->Gamma points

mv Ek.r Ek.r.tmp
sed '1,5s/+/-/' Ek.r.tmp >> Ek.r
rm Ek.r.tmp

# Tidy up

rm -f ank?.r Ek?.r Ek??.r
