#!/bin/sh
set -e

# Find the Fermi-Dirac functions and subband
# energies for a given non-parabolicity value
# parameter 1: The nonparabolicty [1/eV]
solve_for_alpha()
{
    # Calculate Fermi energies and population distributions
    sbp -f -T $T --alpha $1
    mv FD1.r FD1T=$T-np-alpha$1.r
    mv FD2.r FD2T=$T-np-alpha$1.r
    mv FD3.r FD3T=$T-np-alpha$1.r

    # Write Fermi energy of states to file
    printf "%d\t" $T >> Ef1-T-alpha$1.r
    printf "%d\t" $T >> Ef2-T-alpha$1.r
    printf "%d\t" $T >> Ef3-T-alpha$1.r
    awk '/1 /{printf("%8.3f\n",$2)}' Ef.r >> Ef1-T-alpha$1.r
    awk '/2 /{printf("%8.3f\n",$2)}' Ef.r >> Ef2-T-alpha$1.r
    awk '/3 /{printf("%8.3f\n",$2)}' Ef.r >> Ef3-T-alpha$1.r
}

# Initialise files
rm -f Ef?-T*.r N.r FD*.r

lw=200 # Well width
nst=3  # Number of states

# Solve single quantum well
efiw -L $lw -s $nst

# Generate table of populations
N=1
for i in `seq 1 $nst`; do
    echo $i $N >> N.r
done

# Need to artificially create a file v.r containing a barrier height,
# this used as a cut-off energy for population calculations
echo 0.00000 1.60219e-19 > v.r	# i.e., 1eV

alpha=0.701 # Nonparabolicity parameter for GaAs [1/eV]

# Loop for different temperatures
for T in 2 20 40 60 77 100 140 180 220 260 300
do
    solve_for_alpha 0
    solve_for_alpha 0.701
    solve_for_alpha 5
done
