#!/bin/sh
# Calculate alloy profile along z-axis

efpqw --xmax 1

# Convert alloy concentration `x' into effective mass `m'
efxv -m 0.067

# Implement shooting technique
efss --nst-max 3

wfplot --plot-wf
