#!/bin/sh
# Density of states calculation for an infinitely deep square cross-sectional
# quantum wire calculation

# Generate 4 lowest energy solutions 

efiwire -y 60 -z 70 -s 2

# Now calculate density of states, note that the output file `rho.r'
# contains the bulk, quantum well and quantum wire data, plot the latter
# only

dos
