#!/bin/sh
# Define output file

OUT=E-N.r

# Initialise files

rm -f Ee-LAMBDA*
rm -f v-LAMBDA*
rm -f $OUT

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.75

V=626.6175

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x, keep x=0.2

MB=0.12925

# Define a set well width

LW=20

for N in 2 4 6 8 10 12
do
{
 # Calculate lowest 2 levels with analytical form
 efsqw -a $LW -n $MB -V $V
 
 echo -n $N >> $OUT

 # Save lowest two energies to file

 nawk '/1 /{printf("\t%f",$2)}' Ee.r >> $OUT	

 # Now perform numerical solution
 #
 # First generate structure definition `s.r' file
 echo 200 0.75 0.0 > s.r
 echo $LW 0.0 0.0 >> s.r
 echo 200 0.75 0.0 >> s.r

 efsx	-N $N		# generate alloy concentration as a function of z
 efxv			# generate potential data

 efss  		# calculate 2 lowest energy levels
 nawk '/1 /||/2 /{printf("\t%f",$2)}' Ee.r >> $OUT	
 echo -n -e "\n" >> $OUT
}
done
