#!/bin/sh
# Finite square cross-sectional quantum wire calculation
# Generate 4 lowest energy solutions and collate energy eigenvalues as a
# function of well width.  Store the cross-sectional charge densities for
# one well width only.
#
# Quantum wire material GaAs, barrier material Ga(0.8)Al(0.2)As
#
# Define and initialise output file

OUTPUT=Eyz-L.r

rm -f $OUTPUT

# Calculate barrier mass, MB=0.067+0.083*X

MB=0.1002

# Barrier height, V=0.67*1247*X

V=334.196

# Loop over wire side

for L in 50 60 70 80 90 100 120 140 160 200 240 300
do
{
 # Calculate confinement energy and wave function along y-axis
 efsqw -a $L -m 0.067 -n $MB -s 2 -V $V

 # Store energies
 mv Ee.r Ey.r
 
 # Calculate confinement energy and wave function along z-axis
 efsqw -a $L -m 0.067 -n $MB -s 2 -V $V

 # Store energies
 mv Ee.r Ez.r
 
 # Collate and store energy eigenvalues as a function of the wire side

 echo -n $L >> $OUTPUT	# Write well width to file

 # Read Ez values into array and then add them in sequence to Ey values

 nawk 'BEGIN{i=0;while("cat Ez.r"|getline){Ez[i]=$2;i++}}{Ey=$2;printf(" %e %e",Ey+Ez[0],Ey+Ez[1])}' Ey.r >> $OUTPUT

 echo -n -e "\n" >> $OUTPUT	# End line
}
done


