#!/bin/sh
# Define lattice constant

A0=5.43

# Create unstrained zinc blende type crystal

cszb -a SI -c SI -x 2 -y 2 -z 4 -A $A0

# Create heterojunction by substituting atom types, include effects of
# `strain' by stretching z-co-ordinate of atoms beyond the interface

mv atoms.xyz atoms.xyz.tmp		# create temporary file for editing
nawk "{if(\$4>2*$A0) 
       printf(\"GE %9.3f %9.3f %9.3f\n\",\$2,\$3,2*$A0+(\$4-2*$A0)*6.15/$A0)
       else print \$0}" atoms.xyz.tmp >> atoms.xyz

# Convert to pdb format for viewing

xyz2pdb atoms
