#!/bin/sh
# Initialise files
set -e

rm -f Delta-Ee-LW.r

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.4

V=334.1965

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x

MB=0.1002

# Define number of states

S=1

# Loop for well and barrier widths

for LW in 20 25 30 35 40 45 50 55 60 70 80 90 100 120 140 160 180 200
do
{
 # Loop for carrier momentum at centre and edge of Brillouin zone only

 printf "%d\t" "$LW" >> Delta-Ee-LW.r	# write well width to file
 
 for K in 0.0 1.0 
 do
 {
 # Calculate energies for different wave vectors

  efkpsl -a $LW -b $LW -m 0.067 -n $MB --potential $V -k $K -s $S
  nawk '{printf("%9.3f",$2)}' Ee.r >> Delta-Ee-LW.r	# send data to file

 }
 done	# done loop over k

# Compare with energy of single quantum well

efsqw -a $LW -m 0.067 -n $MB --potential $V -s $S
nawk '{printf("%9.3f",$2)}' Ee.r >> Delta-Ee-LW.r	# send data to file
printf "\n" >> Delta-Ee-LW.r		# end line

} done	# loop over LW
