#!/bin/ksh
# GaAs/AlAs in-plane dispersion superlattice calculation with the continuous 
# potentials of Mader and # Zunger et al. Phys. Rev. B (1994)
# Note also the atom types are defined as `GAASmz' and `ASGAmz'
# this selects the Ga in GaAs and As in GaAs potentials

# Define k-vectors, note the cluster of points around Gamma---for m*
# calculation

echo -0.05 0.0 0.0 >  k.r
echo -0.04 0.0 0.0 >> k.r
echo -0.03 0.0 0.0 >> k.r
echo -0.02 0.0 0.0 >> k.r
echo -0.01 0.0 0.0 >> k.r
echo 0.0 0.0 0.0 >> k.r
echo 0.01 0.0 0.0 >> k.r
echo 0.02 0.0 0.0 >> k.r
echo 0.03 0.0 0.0 >> k.r
echo 0.04 0.0 0.0 >> k.r
echo 0.05 0.0 0.0 >> k.r

# Perform calculation for single period only, to illustrate wavefunction

NZ=10

# Create `single-spiral' unit cell akin to superlattice

csss -a ASGAmz -c GAASmz -z $NZ

# Now create superlattice by swapping atoms

mv atoms.xyz atoms.tmp
let A=2*NZ+3		# the first atom to be swapped
let B=4*NZ+2		# the last atom to be swapped
sed "$A,$B s/GA/AL/" atoms.tmp >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# create reciprocal lattice vectors, note use of default maximum |G|

rlv-ss -z $NZ

# Sort the G vectors into ascending order

ppsg

# Output just the bottom conduction band, note
# a structure with a period of NZ has 4NZ atoms, each of which contributes 
# two valence levels, hence the uppermost VB level is the 8NZ.

let N=8*NZ+1	# bottom conduction band
let M=8*NZ+1	# bottom conduction band

# Implement pseudopotential calculation, note use of default lattice constant

pplb -n 1 -m $M

# Collate lowest conduction band energy versus k

ppee -n $N -m $M

# Put -ve sign in for the first  15 k points (just to aid plotting)

mv Ek.r Ek.r.tmp
sed '1,15s/+/-/' Ek.r.tmp >> Ek.r
rm Ek.r.tmp

# Tidy up

rm -f Ek?.r Ek??.r
