#!/bin/sh
# Loop over barrier concentrations

for X in 0.2 0.4 0.6 0.8 1.0
do
{
 # Define output file

 OUT=E-X=$X.r

 # Initialise files

 rm -f $OUT D$OUT

 # Loop over well width

 for LW in 20 40 60 80 100 120 140 160 180 200
 do
 {

 # First generate structure definition `s.r' file
 echo 200 $X 0.0 > s.r
 echo $LW 0.0 0.0 >> s.r
 echo 200 $X 0.0 >> s.r
 
 efsx			# generate alloy concentration as a function of z
 efxv 		# generate potential data, and bandgap
 
 echo -n $LW >> $OUT

 # Calculate ground state energy with band non-parabolicity

 efshoot -a

 # Write energy to output file

 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT	

 # Calculate ground state energy without band non-parabolicity

 efshoot 

 # Write energy to output file

 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT	

 echo -n -e "\n" >> $OUT	# terminate line
 }
 done # LW

 # Now calculate difference between `with' and `without' band non-parabolicity
 # and write to the new output file DE-$X=X.r

 nawk '{printf("%f \t%f\n",$1,$2-$3)}' $OUT >> D$OUT	
}
done # X
