#!/bin/sh
# Calculation of the ratio of the emission to absorption e-LO scattering rate
# averaged over two subband populations, as a function of well width
# Define output file

OUT=sr-T.r

# Define a fixed well width to give E2-E1=36

LW=216


# Initialise files

rm -f $OUT

# Scattering rate codes (at the moment) are angled towards numerical
# solutions and require a potential barrier height as an upper
# for integration, so define an artificial structure
# making sure it contains the same number of points as below

echo 100 1.0 0.0 > s.r
echo 100 0.0 0.0 >> s.r
echo 100 1.0 0.0 >> s.r

# Now convert structure into potential data

efsx
efxv

# Generate infinitely deep well solutions

efiw -L $LW -N 300 -s 2

# Define subband populations in file `N.r'
 
echo 1 1 > N.r
echo 2 1 >> N.r

# Define required scattering rates

echo 2 1 > rrp.r
echo 1 2 >> rrp.r

# Loop over temperature

for T in 4 40 77 120 160 200 240 280 300
do
{
 # Store temperature in output file

 echo -n $T >> $OUT

 # Calculate the distribution functions 

 sbp -T $T
 
 # Calculate scattering rates
 srelo -T $T

 # Write the 2->1 emission rate to the output file
 nawk '/2 1 /{printf(" %e",$3)}' LOe-if.r >> $OUT

 # Write the 1->2 absorption rate to the output file
 nawk '/1 2 /{printf(" %e\n",$3)}' LOa-if.r >> $OUT
}
done
