#! /bin/sh

# Append data to the file Eei-lw.r if the state exists
# Param 1: Number of state
output_E_if_real()
{
 # Extract energies from output file
 Ee=`awk '{print $2}' Ee.r|sed -n "$1p"`
 if test "x$Ee" != "x"; then
	 printf "%f\t%.17e\n" $LW $Ee >> Ee$1-lw.r
 fi
}

# Initialise files
rm -f Ee1-lw.r Ee2-lw.r Ee3-lw.r Ee4-lw.r

# Set fixed parameters
nst=4 # Number of states to find

# Loop for different well widths
for i in `seq 1 0.05 2.3`
do
 # Generate well-widths exponentially so we get a smooth curve at small
 # widths
 LW=`echo $i | awk '{print 10^$1}'`

 # Calculate energy levels
 efsqw -a $LW -s $nst

 # Output energies to file
 for state in `seq 1 $nst`; do
	 output_E_if_real $state
 done
done
