#!/bin/sh
# Define output file

OUT=E-I.r

# Initialise files

rm -f $OUT wf_e1*.r

# Define well width and doping density

LW=100
D=-2		# Note -ve implies `n-type' doping

# First generate structure definition `s.r' file
echo 200 0.2 0.0 0.0  > s.r
echo $LW 0.0 0.0 $D  >> s.r
echo 200 0.2 0.0 0.0 >> s.r
 
# Loop over number of points along z-axis

for N in 10 5 2 1	# reverse loop and hence retain diverging wave functions
do
{
 efsx -N $N		# generate alloy concentration as a function of z
 efxm 			# generate mass versus z data
 efxv			# generate potential data
  
 for I in 0 1 2 3 4 5 6 7
 do
 {
  echo -n $I >> $OUT
 
  # Calculate ground state energy
 
  efshoot
  
  # And wave function
 
  efwf
 
  # save wave function is separate file
 
  cp wf_e1.r wf_e1-I=$I.r


  # Write energy to output file

  nawk '{printf("\t%20.17e\n",$2)}' Ee.r >> $OUT	

  # Implement self consistent Poisson calculation

  scp
 }
 done # X
 
mv E-I.r E-I-N=$N.r
}
done # N
