#!/bin/sh
# Map lambda-zeta parameter space

# Define output file name

OUTPUT=e-zeta-lambda.r

# Initialise files

rm -f $OUTPUT

# Define structure

echo '200 0.1 0.0
100 0.0 0.0
200 0.1 0.0' > s.r

# Creat alloy profile

efsx

# Create potential profile

efxv

# Define donor position

echo '250e-10' > r_d.r

# Initiate variable symmetry donot calculation, note specifying the final
# lambda and zeta values forces this domain to be covered

d0 -s 87 -u 91 -w 0.6 -x 0.02 -y 0.8 > output

# Now collate data in `output' into file suitable for plotting
# Do each zeta value at a time

for ZETA in 6.0 6.2 6.4 6.6 6.8 7.0 7.2 7.4 7.6 7.8
do
{

nawk "BEGIN{printf(\"%e\",$ZETA/10)}/zeta $ZETA/{printf(\" %e\",\$8)}END{printf(\"\\n\")}" output >> $OUTPUT

}
done
