#!/bin/ksh
# GaAs/AlAs superlattice calculation with the continuous potentials of 
# Mader and Zunger et al. Phys. Rev. B (1994)
# Note also the atom types are defined as `GAASmz' and `ASGAmz'
# this selects the Ga in GaAs and As in GaAs potentials

# Define number of lattice constant in superlattice period

NZ=1

csss -a ASGAmz -c GAASmz -z $NZ

# Now create superlattice by swapping atoms

mv atoms.xyz atoms.tmp
let A=2*NZ+3		# the first atom to be swapped
let B=4*NZ+2		# the last atom to be swapped
sed "$A,$B s/GA/AL/" atoms.tmp >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# Define k-vectors

echo 0.0 0.0 0.5  > k.r	
echo 0.0 0.0 0.4 >> k.r
echo 0.0 0.0 0.3 >> k.r
echo 0.0 0.0 0.2 >> k.r
echo 0.0 0.0 0.1 >> k.r
echo 0.0 0.0 0.0 >> k.r
echo 0.0 0.0 0.1 >> k.r
echo 0.0 0.0 0.2 >> k.r
echo 0.0 0.0 0.3 >> k.r
echo 0.0 0.0 0.4 >> k.r
echo 0.0 0.0 0.5 >> k.r
echo 0.0 0.0 0.6 >> k.r
echo 0.0 0.0 0.7 >> k.r
echo 0.0 0.0 0.8 >> k.r
echo 0.0 0.0 0.9 >> k.r
echo 0.0 0.0 1.0 >> k.r

# create reciprocal lattice vectors, note use of default maximum |G|

rlv-ss -z $NZ

# Sort the G vectors into ascending order

ppsg

# Implement pseudopotential calculation, note use of default lattice constant

pplb -n 1 -m 16

# Collate top 2 valence bands and bottom 2 conduction bands, note
# a structure with a period of NZ has 4NZ atoms, each of which contributes 
# two valence levels, hence the uppermost VB level is the 8NZ.

let N=8*NZ-1
let M=8*NZ+2

ppee -n $N -m $M
 
# Need a sed line here to assign negative number to -X->Gamma points

mv Ek.r Ek.r.tmp
sed '1,5s/+/-/' Ek.r.tmp >> Ek.r
rm Ek.r.tmp

# Bulk GaAs calcualtion gave top of valence band as -5.505446 eV, hence add
# this amount to all energy levels

mv Ek.r Ek.r.tmp
nawk '{printf("%10.6f %10.6f %10.6f %10.6f %10.6f\n",$1,$2+5.505446,
 $3+5.505446,$4+5.505446,$5+5.505446)}' Ek.r.tmp >> Ek.r
rm Ek.r.tmp

# Tidy up

rm -f ank?.r Ek?.r Ek??.r
