#!/bin/sh
# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As

X=0.2

# Use V=0.67*1247*x, V(0.1)=83.549, V(0.2)=167.098, V(0.3)=250.647,
# V(0.4)=334.196

V=167.098

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x, MB(0.1)=0.0753, MB(0.2)=0.0836, MB(0.3)=0.0919,
# MB(0.4)=0.1002

MB=0.0836

# Keep well width constant

L2=50

# Keep temperature constant

T=70

for L1 in 30 40 50
do
{ 
 tdb -a $L1 -b $L2 -c $L1 -V $V -n $MB
 ivdb -a $L1 -b $L2 -c $L1 -T $T
 mv T.r TL1=$L1.r
 mv IV.r IVL1=$L1.r
} done
