#!/bin/sh
set -e

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
X=0.2

# Allow barrier composition to be read from command-line
if [ "x$1" != "x" ]; then
    X=$1
fi

# Use V=0.67*1247*x
V=`echo $X | awk '{print 0.67*1247*$1}'`

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x
MB=`echo $X | awk '{print 0.067+0.083*$1}'`

# Keep well width constant
L2=50

# Keep temperature constant
T=70

for L1 in 30 40 50
do
{ 
 tdb -a $L1 -b $L2 --right-barrier-width $L1 --potential $V -n $MB
 ivdb -a $L1 -b $L2 -c $L1 -T $T
 mv T.r TL1=$L1.r
 mv IV.r IVL1=$L1.r
} done
