#!/bin/sh
# Mapping of lambda-energy space for a two-dimensional donor wave function
# in a quantum well

# Generate structure file

echo 200 0.1 0.0 >  s.r
echo 60 0.0 0.0  >> s.r
echo 200 0.1 0.0 >> s.r

# Convert structure file into alloy profile

efsx

# Generate potential profile

efxv -M cdmnte

# Start donor binding energy calculation,
# force output of energy E versus lambda data for lambda=40 to 90A in 2A steps
# in order to illustrate the variational principle

d02D -s 40 -t 2 -u 90 -e 10.6 -m 0.096 > output

# Filter `output' file to give energy versus lambda data

nawk '{printf("%e %e\n",$4,$6)}' output > e-lambda.r
