#! /bin/sh

# Append data to the file Eei-lw.r if the state exists
# Param 1: Number of state
output_E_if_real()
{
 # Extract energies from output file
 Ee=`awk '{print $2}' Ee.r|sed -n "$1p"`
 if test "x$Ee" != "x"; then
	 printf "%d\t%.17e\n" $LW $Ee >> Ee$1-lw.r
 fi
}

# Initialise files
rm -f Ee1-lw.r Ee2-lw.r Ee3-lw.r Ee4-lw.r

# Loop for different well widths

for LW in 10 20 30 40 50 60 70 80 90 100 120 140 160 180 200 
do
 # Calculate first 4 energy levels as a function of well width for GaAs
 efsqw -a $LW -s 4

 # Output energies to file
 for state in `seq 1 4`; do
	 output_E_if_real $state
 done
done
