#!/bin/sh
# LO phonon emission scattering rate for an electron in the second subband
# of an infinitely deep quantum well
# Define temperature

T=77

# Scattering rate codes (at the moment) are angled towards numerical
# solutions and require a potential barrier height as an upper
# for integration, so define an artificial structure
# making sure it contains the same number of points as below

echo 100 1.0 0.0 > s.r
echo 100 0.0 0.0 >> s.r
echo 100 1.0 0.0 >> s.r

# Now convert structure into potential data

efsx
efxv

# Calculate wave functions for an infinitely deep well

efiw -N 300 -s 2

# Define required e-LO phonon rates and calculate 

echo 2 1 > rrp.r

# Calculate e-LO scattering rate

srelo -T $T
