#!/bin/sh
# Bulk InP calculation
# Write crystal basis to file `atoms.xyz' in XYZ format
# Note basis vectors are +/- (1/8,1/8,1/8) and A0=5.86
# Note also the atom types are defined as `INPcb' and `PINcb'
# this selects the IN in INP and P in INP Cohen and Bergstresser (cb)
# potentials

echo 2	> atoms.xyz
echo    >> atoms.xyz				# leave blank line
echo INPcb -0.7325 -0.7325 -0.7325 >> atoms.xyz
echo PINcb  0.7325  0.7325  0.7325 >> atoms.xyz

# Convert also to pdb format for visual check

xyz2pdb atoms

# Define k-vectors

echo 0.5 0.5 0.5  > k.r		# The L point
echo 0.4 0.4 0.4 >> k.r
echo 0.3 0.3 0.3 >> k.r
echo 0.2 0.2 0.2 >> k.r
echo 0.1 0.1 0.1 >> k.r
echo 0.0 0.0 0.0 >> k.r		# Gamma
echo 0.0 0.0 0.1 >> k.r
echo 0.0 0.0 0.2 >> k.r
echo 0.0 0.0 0.3 >> k.r
echo 0.0 0.0 0.4 >> k.r
echo 0.0 0.0 0.5 >> k.r
echo 0.0 0.0 0.6 >> k.r
echo 0.0 0.0 0.7 >> k.r
echo 0.0 0.0 0.8 >> k.r
echo 0.0 0.0 0.9 >> k.r
echo 0.0 0.0 1.0 >> k.r		# X

# create reciprocal lattice vectors, note use of default maximum |G|

rlv-fcc

# Sort the G vectors into ascending order

ppsg

# Implement pseudopotential calculation

pplb -A 5.86 -n 1 -m 6

# Gather first 6 eignenvalues together 

ppee -n 1 -m 6
 
# Need a sed line here to assign negative number to L->Gamma points

mv Ek.r Ek.r.tmp
sed '1,5s/+/-/' Ek.r.tmp >> Ek.r
rm Ek.r.tmp

# Tidy up

rm ank.r Ek?.r Ek??.r
