#!/bin/sh
# Define output files

OUT=E-F.r
OUTsr=sr-F.r

# Initialise files

rm -f $OUT $OUTsr

# Define temperature

T=77

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x, keep x=0.2

V=167.0985

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x, keep x=0.2

MB=0.0836

# Define structure

echo 100 0.2 0.0  > s.r
echo 56.5 0.0 0.0 >> s.r
echo 56.5 0.2 0.0 >> s.r
echo 96.1 0.0 0.0 >> s.r
echo 28.25 0.2 0.0 >> s.r
echo 84.8 0.0 0.0 >> s.r
echo 100 0.2 0.0  >> s.r

efsx			# generate alloy concentration as a function of z
efxv			# generate potential data

# Define required e-e scattering rates, going to ignore 3->1 directly

echo 3 3 3 2  > rr.r
echo 3 3 2 2 >> rr.r
echo 3 2 2 2 >> rr.r
echo 2 2 2 1 >> rr.r
echo 2 2 1 1 >> rr.r
echo 2 1 1 1 >> rr.r

# Define required e-LO rate

echo 3 2  > rrp.r
echo 2 1 >> rrp.r

# Define subband populations

echo 1 10 > N.r
echo 2 10 >> N.r
echo 3 10 >> N.r

# Loop over electric field 

for F in 0  2  4  6 8 10 12 16 20 
do
{
 echo -n $F >> $OUT
 echo -n $F >> $OUTsr

 # Add electric field to potential

 effv -f $F

 # Need a small energy difference to split nearly degenerate levels,
 # calculate three lowest levels

 efshoot -s 3 -d 0.1

 # Write energy to output file

 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT	
 echo -n -e "\n" >> $OUT

 # Calculate subband populations

 sbp -T $T

 # Calculate e-LO scattering rates

 srelo -T $T 
 
 # Perform thermal averaging

 srmpr -T $T

 # Collate results

 nawk '/3 2/{SR32+=$3};/2 1/{SR21+=$3};END{printf(" %e %e",SR32,SR21)}' LOe-if.r >> $OUTsr
 
 # Implement e-e scattering rate calculation

 srcc -T $T

 # Collate results, note anything with /3 2/ in is a 3->2 rate

 nawk '/3 2/{SR32+=$5};/2 1/{SR21+=$5};END{printf(" %e %e",SR32,SR21)}' ccABCD.r >> $OUTsr

 # end line

 echo -n -e "\n" >> $OUTsr
}
done

# Now just recalculate energy levels and wave functions for F=10, say
# for a nice picture

effv -f 10

efshoot -s 3 -d 0.1
