#!/bin/sh
# Calculation of the mean spontaneous radiative emission rate versus
# wavelength

OUT=rad-lambda.r

# Initialise files

rm -f $OUT

# Loop over infinite well width

for LW in 100 200 300 400 500 600
do
{
 # Generate infinitely deep well solutions

 efiw -L $LW -N 300 -s 2

 # Deduce emission wavelength from two subband energies and write to file

 nawk '/1 /{E1=$2};/2 /{E2=$2};END{printf("%20.17e ",6.626e-34*3e+8/((E2-E1)*1.60219e-22))}' Ee.r >> $OUT

 # Calculate 3D scattering rate, sort and store

 srrad -i 2 -f 1 -3 | nawk '/lifetime/{printf("%e ",$3)}' >> $OUT

 # Calculate 2D scattering rate

 srrad -i 2 -f 1    | nawk '/lifetime/{printf("%e ",$3)}' >> $OUT

 # End line in output file

 echo -n -e "\n" >> $OUT

}
done
