#!/bin/sh
# Calculation of the mean e-e scattering rate over two subband populations
# as a function of temperature
# Define output file

OUT=cc-T.r

# Initialise files

rm -f $OUT

# Scattering rate codes (at the moment) are angled towards numerical
# solutions and require a potential barrier height as an upper
# for integration, so define an artificial structure
# making sure it contains the same number of points as below

echo 100 1.0 0.0 > s.r
echo 100 0.0 0.0 >> s.r
echo 100 1.0 0.0 >> s.r

# Now convert structure into potential data

efsx
efxv

# Define the well width

LW=300

# Generate infinitely deep well solutions

efiw -L $LW -N 300 -s 2

# Define the required e-e rate

echo 2 2 1 1 > rr.r

# Write carrier density to file

echo 1 10 > N.r
echo 2 10 >> N.r

# Loop over different temperatures

for T in 4 20 40 77 120 160 220 300
do
{
 # Write temperature to output file

 echo -n $T >> $OUT

 # Calculate the distribution functions

 sbp -T $T
 
 # Calculate carrier-carrier (e-e) scattering rate

 srcc -T $T

 # Sort and store in output file

 nawk '/2 2 1 1/{printf(" %e\n",$5)}' ccABCD.r >> $OUT
}
done

