#!/bin/sh

# Initialise files
rm -f Ee-V.r

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x for x=0.4---keep constant
MB=0.1002
MW=0.067 # Well mass (GaAs)

# Keep well width constant at 100 Angstom
LW=100

# Loop for different barrier heights
for iV in `seq 2 0.1 5`
do
{
 # Generate potentials exponentially so we get a smooth curve at small
 # widths
 V=`echo $iV | awk '{print 10^$1}'`

 printf "%f\t" "$V" >> Ee-V.r	# write potential to file

 # Calculate ground state energy for barrier mass (MB)=well mass (0.067)
 efsqw -a $LW -m $MW -n $MW --potential $V
 awk '{printf("%8.3f",$2)}' Ee.r >> Ee-V.r		# send data to file

 # Calculate ground state energy for different well and barrier masses
 efsqw -a $LW -m $MW -n $MB --potential $V
 awk '{printf("%8.3f\n",$2)}' Ee.r >> Ee-V.r		# send data to file
}
done
