/*==================================================================
       srmpr Scattering Rate---Mean Phonon Rate
  ==================================================================
 
   This program averages a user supplied set of scattering rates
   in the form generated by `srelo' and produces a Fermi-Dirac
   weighted average for command line arguments of temperature 
   carrier density and effective mass

	Input files:
			MMiXX.r		scattering rate

	where MM=LO/AC, i=a/e, XX=11/12/21/22/13/...

	Output files:
			LOif.r		thermally averages rate


   Paul Harrison, June 1996                   
 
   Major modifications, June 1998
   Modifications, January 1999					*/

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <math.h>
#include <signal.h>
#include <malloc.h>
#include "struct.h"
#include "const.h"
#include "maths.h"

typedef
struct	{
 double	E;		    /* total electron energy		  */
 double	SR;		    /* scattering rate            	  */
} data;

main(int argc,char *argv[])
{
double	FD_averageSR();		/* performs a FD weighted average of the
				   scattering rate over a subband	*/
double	*read_Ef();		/* reads Fermi energies from file	*/
double  *read_N();		/* reads subband populations from file	*/
data	*read_data();		/* reads scattering rate file 		*/


double	E_F[2];			/* Fermi energy 0=initial 1=final state	*/
double	*Ef;			/* Fermi energies			*/
double	Ephonon;		/* phonon energy			*/
double	m;			/* effective mass			*/
double	mean_SR;		/* Fermi-Diarc weighted mean SR		*/
double  *N;			/* pointer to subband populations	*/
double	Ne;			/* initial state population		*/
double	T;			/* temperature				*/
int	i_ea;			/* index over emission/absorption 	*/
int	n;			/* number of lines in `filename'	*/
int	nE;			/* number of energies (subbands)	*/
int	state_i;		/* Initial state                        */
int	state_f;		/* Final state                          */
char	e_or_a;			/* Emission 'e' or absorption 'a'	*/
char	mode[11];		/* phonon mode, `AC' or `LO' etc.	*/
char	filename_i[11];		/* input filename			*/
char	filename_o[11];		/* output filename			*/
char	p;			/* particle, e, h or l			*/
data	*data_start_i;		/* start address of potential	 	*/
FILE	*Foutput;		/* pointer to output file		*/
FILE	*Frrp;			/* pointer to required rates file	*/

/* default values */

sprintf(mode,"LO");
state_i=2;
state_f=1;
T=300;
m=0.067*m0;
Ephonon=36*1e-3*e_0;

while((argc>1)&&(argv[1][0]=='-'))
{
 switch(argv[1][1])
 {
  case 'E':
	   Ephonon=atof(argv[2])*1e-3*e_0;
	   break;
  case 'f':
	   state_f=atoi(argv[2]);
           break;
  case 'i':
	   state_i=atoi(argv[2]);
           break;
  case 'm':
           m=atof(argv[2])*m0;
           break;
  case 'M':
	   sprintf(mode,argv[2]);
	   break;
  case 'T':
	   T=atof(argv[2]);
	   break;
  default:
	   printf("Usage: srmpr [-E phonon energy (\033[1m36\033[0mmeV)][-m mass (\033[1m0.067\033[0mm0)]\n");
	   printf("             [-M mode (AC, \033[1mLO\033[0m)][-T temperature (\033[1m300\033[0mK)]\n");
	   exit(0);

 }
 argv++;
 argv++;
 argc--;
 argc--;
}

Ef=read_Ef(p,&nE);	/* read in Fermi energies       */
N=read_N(nE);		/* read in subband populations  */

/* Calculate weighted means for both emission (e) and absorption (a)	*/

for(i_ea=0;i_ea<=1;i_ea++)
{
 if(i_ea==0)e_or_a='e';	/* Convert integer to character representation	*/
  else {e_or_a='a';Ephonon*=-1;} /* accounts for phonon absorption	*/

 /* Open output file */

 sprintf(filename_o,"%s%c-if.r",mode,e_or_a);
 Foutput=fopen(filename_o,"w");

 /* Open required rates (phonons) file `rrp.r'	*/

 Frrp=fopen("rrp.r","r");

 while(fscanf(Frrp,"%i %i",&state_i,&state_f)!=EOF)
 {
  /* Assign input filename	*/

  sprintf(filename_i,"%s%c%i%i.r",mode,e_or_a,state_i,state_f);

  data_start_i=read_data(&n,filename_i);		/* reads SR file*/

  E_F[0]=*(Ef+state_i-1);
  E_F[1]=*(Ef+state_f-1);
 
  Ne=*(N+state_i-1);

  mean_SR=FD_averageSR(data_start_i,E_F,Ephonon,m,n,Ne,T);

  /* Write data to output file	*/

  fprintf(Foutput,"%i %i %20.17le\n",state_i,state_f,mean_SR);

  free(data_start_i);

 }/* end while over rrp.r data	*/

 fclose(Frrp);
 fclose(Foutput);
 
}/* end for loop over i_ea	*/


} /* end main */





double
FD_averageSR(data_start,E_F,Ephonon,m,n,Ne,T)


/* This function averages the intersubband scattering rate over the 
   whole subband, weighted according to the Fermi-Dirac distribution
   function f(E)

            Emax
   mean SR= I    SR(E) f_i(E) (1-f_f(E-Ephonon))  dE
            Emin
            ----------------------------------------
                  Emax
                  I    f_i(E) dE=Ne pi hbar^2/m
                  Emin
  
   where Emax and Emin are the maximum (top of well) and minimum energies 
   of the initial subband.
  
									*/
  

data    *data_start;            /* start address of potential           */
double  E_F[];                  /* Fermi energy                         */
double	Ephonon;		/* phonon energy			*/
double  m;                      /* effective mass                       */
int     n;                      /* number of lines in `filename'        */
double  Ne;			/* number of electrons/unit area        */
double  T;                      /* temperature                          */
{
double	dE;			/* strip width for integration		*/
double	mean_SR=0;
int	i;


/* Simple integration, sum of ordinate x strip width' 	*/

for(i=0;i<n-1;i++)	/* miss last ordinate	*/
{
 dE=((data_start+i+1)->E)-((data_start+i)->E);
 mean_SR+=((data_start+i)->SR)/(exp((((data_start+i)->E)-E_F[0])/(kb*T))+1)
         *(1-1/(exp((((data_start+i)->E)-Ephonon-E_F[1])/(kb*T))+1))*dE;
}

mean_SR/=(Ne*pi*sqr(hbar)/m);

return(mean_SR);

}



data
*read_data(n,filename)

/* This function reads the potential into memory and returns the start
   address of this block of memory and the number of lines	   */

int	*n;
char	filename[];	/* filename string				*/

{
 FILE 	*Fsr;		/* file pointer to scattering rate file		*/
 data	*fdata;		/* temporary pointer to data			*/
 data	*data_start;	/* start address of data			*/

 if((Fsr=fopen(filename,"r"))==0)
 {
   fprintf(stderr,"Error: Cannot open input file '%s'!\n",filename);
   exit(0);
 }

 *n=0;
 while(fscanf(Fsr,"%*le %*le")!=EOF)
  (*n)++;
 rewind(Fsr);

 data_start=(data *)calloc(*n,sizeof(data));
 if (data_start==0)  {
  fprintf(stderr,"Cannot allocate memory!\n");
  exit(0);
 }

 fdata=data_start;

 while(fscanf(Fsr,"%le %le",&(fdata->E),&(fdata->SR))!=EOF)
 {
  (fdata->E)*=1e-3*e_0;		/*convert meV->J		*/
  fdata++;
 }

 fclose(Fsr);

 return(data_start);

}



double
*read_Ef(p,nE)

/* This function reads the potential into memory and returns the start
   address of this block of memory and the number of lines         */

char	p;
int	*nE;

{
 double *Ef;
 int    i=0;            /* index over the energies                      */
 char   filename[9];    /* filename string                              */
 FILE   *FEf;           /* file pointer to energy data                  */

 sprintf(filename,"Ef.r",p);    /* Retain general structure for another day
*/
 if((FEf=fopen(filename,"r"))==0)
 {
   fprintf(stderr,"Error: Cannot open input file '%s'!\n",filename);
   exit(0);
 }

 *nE=0;
 while(fscanf(FEf,"%*i %*le")!=EOF)
  (*nE)++;
 rewind(FEf);

 Ef=(double *)calloc(*nE,sizeof(double));
 if (Ef==0)  {
  fprintf(stderr,"Cannot allocate memory!\n");
  exit(0);
 }

 while(fscanf(FEf,"%*i %le",Ef+i)!=EOF)
 {
  *(Ef+i)*=1e-3*e_0;            /*convert meV->J                */
  i++;
 }

 fclose(FEf);

 return(Ef);
}



double
*read_N(nE)

/* This function reads the subband populations into memory and returns
   the start address of this block of memory       */

int     nE;

{
 double *N;
 int    i=0;            /* index over the energies                      */
 char   filename[9];    /* filename string                              */
 FILE   *FN;            /* file pointer to subband populations data     */

 if((FN=fopen("N.r","r"))==0)
 {
   fprintf(stderr,"Error: Cannot open input file 'N.r'!\n");
   exit(0);
 }

 N=(double *)calloc(nE,sizeof(double));
 if (N==0)  {
  fprintf(stderr,"Cannot allocate memory!\n");
  exit(0);
 }

 while(fscanf(FN,"%*i %le",N+i)!=EOF)
 {
  *(N+i)*=1e+10*1e+4;   /*convert from units of 10^10cm^-2->m^-2 */
  i++;
 }

 fclose(FN);

 return(N);
}

