#!/bin/sh

# Initialise files
rm -f Ee-lw.r

# Read the barrier alloy from command-line argument
if [ "z$1" = "z" ]; then
    echo "You need to specify the barrier alloy as an argument to this script"
    echo "For example, to use 10% alloy in the barrier, enter:"
    echo "  $0 0.1"
    exit 1
else
    x=$1
fi

# Calculate conduction band barrier height for GaAs/Ga(1-x)Al(x)As
# Use V=0.67*1247*x
V=`echo 0.67*1247*$x|bc`

# Calculate bulk effective mass of electron in Ga(1-x)Al(x)As
# Use MB=0.067+0.083*x
MB=`echo 0.067 + 0.083*$x|bc`
MW=0.067 # Well mass (GaAs)

# Loop for different well widths
for LW in 10 20 30 40 50 60 70 80 90 100 120 140 160 180 200 
do
{
 printf "%d\t" "$LW" >> Ee-lw.r	# write well width to file

 # Calculate ground state energy for barrier mass (MB)=well mass (0.067)
 efsqw -a $LW -m $MW -n $MW --potential $V --output-equations
 mv rhs.r rhs-const.r
 mv lhs.r lhs-const.r
 awk '{printf("%8.3f",$2)}' Ee.r >> Ee-lw.r		# send data to file

 # Calculate ground state energy for correct barrier mass 
 efsqw -a $LW -m $MW -n $MB --potential $V --output-equations
 mv rhs.r rhs-mb.r
 mv lhs.r lhs-mb.r
 awk '{printf("%8.3f\n",$2)}' Ee.r >> Ee-lw.r		# send data to file
}
done

cp Ee-lw.r x\=$x-Ee-lw.r
