#!/bin/sh
# GaAs/AlAs Kronig-Penney superlattice calculation for comparison with the 
# pseudopotential of the previous section.

OUTPUT=Ee-Nz.r
rm -f $OUTPUT

# Loop over the equal well and barrier widths, values are equivalent to
# (a+b)=NZ*A0 of before, recall A0=5.65 Angstroms

for A in 2.825 5.65 8.475 11.3 14.125 16.95 19.775 22.6 25.426 28.25 33.9 39.55 45.2 50.85
do
{
# Perform Kronig-Penney calculation, note use of parameters from the same
# source as the pseudopotentials, i.e., Mader and Zunger, Phys. Rev. B50
# 17393 (1994), Table II.

efkpsl -a $A -b $A -m 0.099 -n 0.179 -V 1003

# Now collate results in a file, note more complex `nawk' format---the use
# of " rather than ', this allows incorporation of the shell variable $A
# into output file.  Note also the addition of the band gap onto the
# electron energy levels

nawk "{printf(\"%f %e\n\",$A *2/5.65,\$2/1000+1.499)}" Ee.r >> $OUTPUT

}
done
