#!/bin/sh
# Initialise files

rm -f Ee-lw.r

# Loop for different well widths

for LW in 10 20 30 40 50 60 70 80 90 100 120 140 160 180 200 
do
{
 # Calculate first 4 energy levels as a function of well width for GaAs

 efsqw -a $LW -s 4	

 echo -e "$LW\t" >> Ee-lw.r	# write well width to file
 cat Ee.r >> Ee-lw.r		# send data to file

}
done
