#!/bin/sh
# Loop over barrier concentrations

# Define output file

OUT=E-I.r

# Initialise files

rm -f $OUT wf_e1*.r

# Define well width and doping density

LW=100
D=-1		# Note -ve implies `n-type' doping

# First generate structure definition `s.r' file
echo 200 0.2 0.0 0.0  > s.r
echo $LW 0.0 0.0 $D  >> s.r
echo 200 0.2 0.0 0.0 >> s.r
 
 efsx 			# generate alloy concentration as a function of z
 efxv			# generate potential data
  
for I in 0 1 2 3 4 5 6 7 
do
{
 echo -n $I >> $OUT

 # Calculate ground state energy

 efshoot
 
 # save wave function is separate file

 cp wf_e1.r wf_e1-I=$I.r


 # Write energy to output file

 nawk '{printf("\t%20.17e\n",$2)}' Ee.r >> $OUT	

 # Implement self consistent Poisson calculation

 scp
}
done # X
