#!/bin/ksh
# Note this file is a ksh script, need integer arithmetic
# Define output file

OUT=E-N.r

# Initialise files

rm -f Ee-LAMBDA*
rm -f v-LAMBDA*
rm -f $OUT

# Loop over number of points per Angstrom

for N in 1 2 5 10 20 50 100
do
{
 # Define length of Poschl-Teller potential
 L=300

 pth -a 0.05 -l 5 -L $L -N $N
 echo -n $N >> $OUT

 # Save lowest two energies to file

 nawk '/1 /||/2 /{printf("\t%f",$2)}' Ee.r >> $OUT	

 # Now perform numerical solution
 #
 # Need to add extra point
 let L=N*L+1
 # Then generate artificial s.r file, necessary to produce mass data
 echo $L 0.0 0.0 > s.r
 efsx			# generates z-data suitable for numerical solution
 efxv -m 0.067		# generate constant mass versus z data
 efshoot -s 2		# calculate 2 lowest energy levels
 nawk '{printf("\t%f",$2)}' Ee.r >> $OUT
 echo -n -e "\n" >> $OUT
}
done
